/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void statustoSaveFolder() {
        SaveParser saveParser = new SaveParser();
        Game game = new Game();
        saveParser.statustoSaveFolder(game,"Archive I");
    }

    @Test void saveFoldertoStatus() {
        SaveParser saveParser = new SaveParser();
        saveParser.saveFoldertoStatus("Archive I");
    }
}
